/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/account/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout user */
    post: operations["AccountController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account/verify/resend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend verification email */
    post: operations["AccountController_resendVerifyEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change password */
    post: operations["AccountController_changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get session by id */
    get: operations["SessionController_getSessionById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all user sessions */
    get: operations["SessionController_getAllUserSessions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/revoke/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a user session */
    post: operations["SessionController_revokeSessionById"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke all user sessions */
    post: operations["SessionController_revokeAllSessions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user information */
    get: operations["UserController_userInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user/update/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update user information */
    put: operations["UserController_updateUser"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user/image/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload user image */
    post: operations["UserController_imageUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new account */
    post: operations["AuthController_register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login an account */
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh token */
    post: operations["AuthController_refreshToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verify email */
    get: operations["AuthController_verify"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check health status */
    get: operations["HealthController_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/urls": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all short URLs for a user */
    get: operations["UrlsController_getUrls"];
    put?: never;
    /** Create a new short URL */
    post: operations["UrlsController_createUrls"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/urls/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a short URL by id */
    get: operations["UrlsController_getUrlById"];
    /** Update a short URL */
    put: operations["UrlsController_updateUrl"];
    post?: never;
    /** Delete a short URL */
    delete: operations["UrlsController_deleteUrl"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/urls/shorten": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Shorten a URL for public access */
    post: operations["PublicUrlsController_shortenUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/urls/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a short URL for public access */
    get: operations["PublicUrlsController_getUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/urls/unlock/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unlock a short URL for public access */
    post: operations["PublicUrlsController_unlockUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/active": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user active subscription */
    get: operations["SubscriptionsController_getUserActiveSubscription"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/active/cycles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all active subscription cycles */
    get: operations["SubscriptionsController_getUserActiveSubscriptionCycles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get subscription by id */
    get: operations["SubscriptionsController_getSubscriptionById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/{id}/cycles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all subscription cycles */
    get: operations["SubscriptionsController_getAllUserSubscriptionCycles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/{id}/cycles/{cycleId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get subscription cycle by id */
    get: operations["SubscriptionsController_getUserSubscriptionCycleById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/{id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deactivate subscription plan */
    post: operations["SubscriptionsController_deactivateSubscription"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/{id}/plans/upgrade": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upgrade subscription plan */
    post: operations["SubscriptionsController_upgradeSubscriptionPlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subscriptions/{id}/plans/upgrade/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SubscriptionsController_getAllUpgradePlanOptions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-methods/requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get requested payment methods */
    get: operations["PaymentMethodsController_requestPaymentMethod"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-methods/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get payment method by id */
    get: operations["PaymentMethodsController_getPaymentMethodById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-methods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all payment methods */
    get: operations["PaymentMethodsController_getAllPaymentMethods"];
    put?: never;
    /** Create payment method */
    post: operations["PaymentMethodsController_createPaymentMethod"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payment-methods/sort": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sort payment methods */
    patch: operations["PaymentMethodsController_sortPaymentMethods"];
    trace?: never;
  };
  "/api/v1/public/payment-methods/add": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Add payment method */
    get: operations["PublicPaymentMethodsController_addPaymentMethod"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/payment-methods/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate payment method */
    post: operations["PublicPaymentMethodsController_validatePaymentMethod"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/payment-methods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create payment method */
    post: operations["PublicPaymentMethodsController_createPaymentMethod"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/webhooks/xendit/payment_methods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Handle Xendit payment methods callback data */
    post: operations["WebhooksController_handleXenditPaymentMethods"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/webhooks/xendit/recurring": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Handle Xendit recurring plan callback data */
    post: operations["WebhooksController_handleXenditRecurring"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all transactions */
    get: operations["TransactionsController_getAllTransactions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transactions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get transaction by id */
    get: operations["TransactionsController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ZodString: Record<string, never>;
    ChangePasswordDto: {
      old_password: string;
      new_password: string;
      confirm_password: string;
    };
    UserInfoResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        /** Format: email */
        email: string;
        username: string;
        full_name: string;
        phone_number?: string | null;
        /**
         * @default user
         * @enum {string}
         */
        role: "admin" | "user";
        /** Format: uri */
        avatar?: string | null;
        providers: {
          /**
           * @default local
           * @enum {string}
           */
          provider: "local" | "google";
          /** @default false */
          is_verified: boolean;
        };
        last_login_at: unknown;
      };
      /** @default 2025-11-04T06:21:27.972Z */
      timestamp: string;
    };
    SessionInfoResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        user_agent: string | null;
        ip_location: string | null;
        /** @default false */
        is_revoked: boolean;
        revoked_at: unknown;
        expires_at: unknown;
        user: {
          /** Format: uuid */
          id: string;
          created_at: string | unknown;
          updated_at: string | unknown;
          /** Format: email */
          email: string;
          username: string;
          full_name: string;
          phone_number?: string | null;
          /**
           * @default user
           * @enum {string}
           */
          role: "admin" | "user";
          /** Format: uri */
          avatar?: string | null;
          providers: {
            /**
             * @default local
             * @enum {string}
             */
            provider: "local" | "google";
            /** @default false */
            is_verified: boolean;
          };
          last_login_at: unknown;
        };
      };
      /** @default 2025-11-04T06:21:28.037Z */
      timestamp: string;
    };
    SessionsInfoResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        user_agent: string | null;
        ip_location: string | null;
        /** @default false */
        is_revoked: boolean;
        revoked_at: unknown;
        expires_at: unknown;
        user: {
          /** Format: uuid */
          id: string;
          created_at: string | unknown;
          updated_at: string | unknown;
          /** Format: email */
          email: string;
          username: string;
          full_name: string;
          phone_number?: string | null;
          /**
           * @default user
           * @enum {string}
           */
          role: "admin" | "user";
          /** Format: uri */
          avatar?: string | null;
          providers: {
            /**
             * @default local
             * @enum {string}
             */
            provider: "local" | "google";
            /** @default false */
            is_verified: boolean;
          };
          last_login_at: unknown;
        };
      }[];
      /** @default 2025-11-04T06:21:28.037Z */
      timestamp: string;
    };
    UpdateUserBodyDto: {
      username?: string;
      full_name?: string;
      /** Format: email */
      email?: string;
      phone_number?: string | null;
      /** Format: uri */
      avatar?: string | null;
    };
    RegisterBodyDto: {
      full_name: string;
      username: string;
      /** Format: email */
      email: string;
      password: string;
      confirm_password: string;
      phone_number?: string | null;
    };
    LoginBodyDto: {
      username: string;
      password: string;
    };
    AuthenticatedResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        tokens: {
          access_token: string;
          refresh_token: string;
        };
        user: {
          /** Format: uuid */
          id: string;
          created_at: string | unknown;
          updated_at: string | unknown;
          /** Format: email */
          email: string;
          username: string;
          full_name: string;
          phone_number?: string | null;
          /**
           * @default user
           * @enum {string}
           */
          role: "admin" | "user";
          /** Format: uri */
          avatar?: string | null;
          providers: {
            /**
             * @default local
             * @enum {string}
             */
            provider: "local" | "google";
            /** @default false */
            is_verified: boolean;
          };
          last_login_at: unknown;
        };
      };
      /** @default 2025-11-04T06:21:28.176Z */
      timestamp: string;
    };
    TokensResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        access_token: string;
        refresh_token: string;
      };
      /** @default 2025-11-04T06:21:28.176Z */
      timestamp: string;
    };
    UserInfoDto: {
      /** Format: uuid */
      id: string;
      created_at: string | unknown;
      updated_at: string | unknown;
      /** Format: email */
      email: string;
      username: string;
      full_name: string;
      phone_number?: string | null;
      /**
       * @default user
       * @enum {string}
       */
      role: "admin" | "user";
      /** Format: uri */
      avatar?: string | null;
      providers: {
        /**
         * @default local
         * @enum {string}
         */
        provider: "local" | "google";
        /** @default false */
        is_verified: boolean;
      };
      last_login_at: Record<string, never> | null;
    };
    ShortenUrlDto: {
      code?: string;
      /** Format: uri */
      original_url: string;
      /** @default false */
      is_protected: boolean;
      access_code?: string;
      expires_at?: Record<string, never>;
      channel_ids?: string[];
    };
    UrlResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        code: string;
        /** Format: uri */
        original_url: string;
        /** @default true */
        is_anonymous: boolean;
        /** @default false */
        is_protected: boolean;
        access_code: string | null;
        expires_at: unknown;
        /** @default 0 */
        click_count: number;
        metadata: {
          title?: string;
          description?: string;
          /** Format: uri */
          image?: string;
          /** Format: uri */
          favicon?: string;
          site_name?: string;
        } | null;
        channels: {
          /** Format: uuid */
          id: string;
          name: string;
          description: string | null;
        }[];
      };
      /** @default 2025-11-04T06:21:28.252Z */
      timestamp: string;
    };
    AllUrlsResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        code: string;
        /** Format: uri */
        original_url: string;
        /** @default true */
        is_anonymous: boolean;
        /** @default false */
        is_protected: boolean;
        access_code: string | null;
        expires_at: unknown;
        /** @default 0 */
        click_count: number;
        metadata: {
          title?: string;
          description?: string;
          /** Format: uri */
          image?: string;
          /** Format: uri */
          favicon?: string;
          site_name?: string;
        } | null;
        channels: {
          /** Format: uuid */
          id: string;
          name: string;
          description: string | null;
        }[];
      }[];
      /** @default 2025-11-04T06:21:28.253Z */
      timestamp: string;
    };
    UpdateUrlDto: {
      code?: string;
      /** Format: uri */
      original_url?: string;
      /** @default true */
      is_anonymous: boolean;
      /** @default false */
      is_protected: boolean;
      access_code?: string | null;
      expires_at?: Record<string, never> | null;
      metadata?: {
        title?: string;
        description?: string;
        /** Format: uri */
        image?: string;
        /** Format: uri */
        favicon?: string;
        site_name?: string;
      } | null;
      channels?: {
        /** Format: uuid */
        id: string;
        name: string;
        description: string | null;
      }[];
    };
    PublicUrlResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        created_at: string | unknown;
        updated_at: string | unknown;
        code: string;
        /** Format: uri */
        original_url: string;
        /** @default true */
        is_anonymous: boolean;
        /** @default false */
        is_protected: boolean;
        expires_at: unknown;
        /** @default 0 */
        click_count: number;
        metadata: {
          title?: string;
          description?: string;
          /** Format: uri */
          image?: string;
          /** Format: uri */
          favicon?: string;
          site_name?: string;
        } | null;
      };
      /** @default 2025-11-04T06:21:28.252Z */
      timestamp: string;
    };
    ForbiddenResponse: {
      /** @default false */
      success: boolean;
      /** @default 403 */
      status: number;
      message?: string;
      /** @default Forbidden Exception */
      error: unknown | string;
      path: string;
      /** @default 2025-11-04T06:21:28.256Z */
      timestamp: string;
    };
    UnlockUrlDto: {
      access_code: string;
    };
    SubscriptionInfoResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        reference_id: string | null;
        external_id: string | null;
        /** Format: uuid */
        user_id: string;
        plan: {
          /** @enum {string} */
          name: "Free" | "Pro" | "Enterprise";
          limit: number;
          reset_interval: string;
          cost: number;
          /** @default false */
          charge_on_success: boolean;
          description: string | null;
          price: number;
        };
        started_at: unknown;
        expires_at: unknown;
        remaining: number;
        /** @enum {string} */
        status:
          | "ACTIVE"
          | "INACTIVE"
          | "CANCELED"
          | "PENDING"
          | "EXPIRED"
          | "SUSPENDED";
        /** @default false */
        is_trial: boolean;
        schedule: {
          /** @enum {string} */
          interval: "DAY" | "WEEK" | "MONTH" | "YEAR";
          interval_count: number;
          total_recurrence: number;
        } | null;
        metadata: {
          /** @enum {string} */
          strategy: "UPGRADE_IMMEDIATELY" | "FINISH_CURRENT_CYCLE";
          /** @enum {string} */
          previous_plan: "Free" | "Pro" | "Enterprise";
          /** @enum {string} */
          new_plan: "Free" | "Pro" | "Enterprise";
        } | null;
        transaction_status: string | null;
        next_billing_date: unknown;
        actions?: {
          action: string;
          url_type: string;
          /** Format: uri */
          url: string;
          /** @default GET */
          method: string;
        }[];
      };
      /** @default 2025-11-04T06:21:28.683Z */
      timestamp: string;
    };
    ListSubscriptionCyclesResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        /** Format: uuid */
        subscription_id: string;
        action_ids: string[];
        /** Format: uuid */
        transaction_id: string | null;
        type: string;
        /** @enum {string} */
        status: "SCHEDULED" | "RETRYING" | "FAILED" | "SUCCEEDED" | "CANCELLED";
        payment_link_failed_retry: string | null;
        cycle_number: number;
        attempt_count: number;
        failure_code: string | null;
        scheduled_date: unknown;
      }[];
      /** @default 2025-11-04T06:21:28.683Z */
      timestamp: string;
    };
    SubscriptionCycleResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        /** Format: uuid */
        subscription_id: string;
        action_ids: string[];
        /** Format: uuid */
        transaction_id: string | null;
        type: string;
        /** @enum {string} */
        status: "SCHEDULED" | "RETRYING" | "FAILED" | "SUCCEEDED" | "CANCELLED";
        payment_link_failed_retry: string | null;
        cycle_number: number;
        attempt_count: number;
        failure_code: string | null;
        scheduled_date: unknown;
      }[];
      /** @default 2025-11-04T06:21:28.683Z */
      timestamp: string;
    };
    UpgradeSubscriptionDto: {
      /** @enum {string} */
      plan: "Free" | "Pro" | "Enterprise";
      /**
       * @default UPGRADE_IMMEDIATELY
       * @enum {string}
       */
      strategy: "UPGRADE_IMMEDIATELY" | "FINISH_CURRENT_CYCLE";
      amount?: number;
      discount?: number;
      schedule: {
        /**
         * @default MONTH
         * @enum {string}
         */
        interval: "DAY" | "WEEK" | "MONTH" | "YEAR";
        /** @default 1 */
        interval_count: number;
        /** @default 12 */
        total_recurrence: number;
      };
      description: string;
    };
    UpgradePlanOptionResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        /** @enum {string} */
        name: "Free" | "Pro" | "Enterprise";
        limit: number;
        reset_interval: string;
        cost: number;
        /** @default false */
        charge_on_success: boolean;
        description: string | null;
        price: number;
        upgradable: boolean;
        options: {
          /** @enum {string} */
          strategy: "UPGRADE_IMMEDIATELY" | "FINISH_CURRENT_CYCLE";
          upgradable: boolean;
          /** @enum {string} */
          current_plan: "Free" | "Pro" | "Enterprise";
          /** @enum {string} */
          new_plan: "Free" | "Pro" | "Enterprise";
          amount: number;
          discount: number;
          remaining_days: number;
          remaining_credit: number;
          net_amount: number;
        }[];
      };
      /** @default 2025-11-04T06:21:28.682Z */
      timestamp: string;
    };
    ListPaymentMethodActionResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        action: string;
        /** Format: uri */
        url: string;
        /**
         * @default GET
         * @enum {string}
         */
        method: "GET" | "POST" | "PUT" | "DELETE";
      }[];
      /** @default 2025-11-04T06:21:28.679Z */
      timestamp: string;
    };
    PaymentMethodResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        /** Format: uuid */
        user_id: string;
        external_id: string;
        /** @enum {string} */
        type:
          | "CARD"
          | "EWALLET"
          | "DIRECT_DEBIT"
          | "VIRTUAL_ACCOUNT"
          | "QRCODE"
          | "OTC"
          | "OTHER";
        reusability: string | null;
        country: string | null;
        currency: string | null;
        status: string | null;
        channel_code: string | null;
        provider: string | null;
        failure_code: string | null;
        custom_name: string | null;
        card: {
          network: string | null;
          issuer: string | null;
          card_type: string | null;
          masked_card_number: string | null;
          expiry_month: string | null;
          expiry_year: string | null;
          card_holder_name: string | null;
        } | null;
        direct_debit: {
          bank_account_number: string | null;
          bank_account_hash: string | null;
        } | null;
        ewallet: {
          account_name: string | null;
          account_number: string | null;
          payment_code: string | null;
          qr_string: string | null;
          expires_at: string | null;
        } | null;
        recurring_expiry: unknown;
        recurring_frequency: number | null;
        is_default: boolean;
        rank: number;
        metadata: {
          [key: string]: unknown;
        } | null;
      };
      /** @default 2025-11-04T06:21:28.687Z */
      timestamp: string;
    };
    AllPaymentMethodsResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        /** Format: uuid */
        user_id: string;
        external_id: string;
        /** @enum {string} */
        type:
          | "CARD"
          | "EWALLET"
          | "DIRECT_DEBIT"
          | "VIRTUAL_ACCOUNT"
          | "QRCODE"
          | "OTC"
          | "OTHER";
        reusability: string | null;
        country: string | null;
        currency: string | null;
        status: string | null;
        channel_code: string | null;
        provider: string | null;
        failure_code: string | null;
        custom_name: string | null;
        card: {
          network: string | null;
          issuer: string | null;
          card_type: string | null;
          masked_card_number: string | null;
          expiry_month: string | null;
          expiry_year: string | null;
          card_holder_name: string | null;
        } | null;
        direct_debit: {
          bank_account_number: string | null;
          bank_account_hash: string | null;
        } | null;
        ewallet: {
          account_name: string | null;
          account_number: string | null;
          payment_code: string | null;
          qr_string: string | null;
          expires_at: string | null;
        } | null;
        recurring_expiry: unknown;
        recurring_frequency: number | null;
        is_default: boolean;
        rank: number;
        metadata: {
          [key: string]: unknown;
        } | null;
      }[];
      /** @default 2025-11-04T06:21:28.687Z */
      timestamp: string;
    };
    SortPaymentMethodsDto: {
      root?: {
        /** Format: uuid */
        payment_method_id: string;
        rank: number;
      }[];
    };
    CreatePaymentMethodDto: {
      /** @enum {string} */
      type: "EWALLET" | "DIRECT_DEBIT";
      ewallet?: {
        /** @enum {string} */
        channel_code: "DANA" | "SHOPEEPAY";
      } | null;
      direct_debit?: {
        /** @enum {string} */
        channel_code: "MANDIRI" | "BPI";
      } | null;
      /** @default false */
      default: boolean;
      /** Format: uri */
      success_return_url: string;
      /** Format: uri */
      failure_return_url: string;
    };
    PaymentMethodActionResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        action: string;
        /** Format: uri */
        url: string;
        /**
         * @default GET
         * @enum {string}
         */
        method: "GET" | "POST" | "PUT" | "DELETE";
      };
      /** @default 2025-11-04T06:21:28.679Z */
      timestamp: string;
    };
    ValidatePaymentMethodDto: {
      /** @enum {string} */
      type: "CARD" | "EWALLET" | "DIRECT_DEBIT";
      card?: {
        card_type: string | null;
        masked_card_number: string | null;
        expiry_month: string | null;
        expiry_year: string | null;
      } | null;
      ewallet?: {
        /** @enum {string} */
        channel_code: "DANA" | "SHOPEEPAY";
      } | null;
      direct_debit?: {
        /** @enum {string} */
        channel_code: "MANDIRI" | "BPI";
      } | null;
    };
    OkResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** @default OK */
        message: string;
      };
      /** @default 2025-11-04T06:21:27.971Z */
      timestamp: string;
    };
    ListTransactionsResponse: {
      success: boolean;
      /** @default 200 */
      status: number;
      path: string;
      data: {
        /** Format: uuid */
        id: string;
        created_at: string | unknown;
        updated_at: string | unknown;
        /** Format: uuid */
        user_id: string;
        /** Format: uuid */
        cycle_id: string;
        /** Format: uuid */
        payment_method_id: string;
        /** Format: uuid */
        subscription_id: string;
        reference_id: string;
        product_name: string;
        amount: number;
        currency: string | null;
        /** @enum {string} */
        status: "PENDING" | "PAID" | "FAILED" | "REFUSED" | "REFUNDED";
        payment_method_type: string;
        /** @enum {string} */
        payment_type: "PAYMENT_LINK" | "PAYMENT_REQUEST";
        metadata: Record<string, never> | null;
        paid_at: unknown;
        failed_at: unknown;
        failure_code: string | null;
        refunded_at: unknown;
        invoice_id: string | null;
        invoice_url: string | null;
        invoice_number: string | null;
        invoice_pdf_path: string | null;
      }[];
      /** @default 2025-11-04T06:21:28.696Z */
      timestamp: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AccountController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logout successful */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccountController_resendVerifyEmail: {
    parameters: {
      query?: never;
      header?: {
        /** @description Client URL */
        "x-client-url"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Resend verify email successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ZodString"];
        };
      };
      /** @description Resend verify email unsuccessful */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ZodString"];
        };
      };
    };
  };
  AccountController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDto"];
      };
    };
    responses: {
      /** @description Change password successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInfoResponse"];
        };
      };
    };
  };
  SessionController_getSessionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get session by id successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionInfoResponse"];
        };
      };
    };
  };
  SessionController_getAllUserSessions: {
    parameters: {
      query: {
        isActive: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get all user sessions successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionsInfoResponse"];
        };
      };
    };
  };
  SessionController_revokeSessionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SessionController_revokeAllSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_userInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get user information successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInfoResponse"];
        };
      };
    };
  };
  UserController_updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserBodyDto"];
      };
    };
    responses: {
      /** @description Update user information successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInfoResponse"];
        };
      };
    };
  };
  UserController_imageUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      /** @description Upload user image successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInfoResponse"];
        };
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: {
        /** @description Client URL */
        "x-client-url"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterBodyDto"];
      };
    };
    responses: {
      /** @description Registration successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthenticatedResponse"];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginBodyDto"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthenticatedResponse"];
        };
      };
    };
  };
  AuthController_refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refresh token successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokensResponse"];
        };
      };
    };
  };
  AuthController_verify: {
    parameters: {
      query: {
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Verify email successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInfoDto"];
        };
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example ok */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example error */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  UrlsController_getUrls: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get all short URLs for a user successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AllUrlsResponse"];
        };
      };
    };
  };
  UrlsController_createUrls: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShortenUrlDto"];
      };
    };
    responses: {
      /** @description Created a new short URL */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UrlResponse"];
        };
      };
    };
  };
  UrlsController_getUrlById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get a short URL by id successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UrlResponse"];
        };
      };
    };
  };
  UrlsController_updateUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUrlDto"];
      };
    };
    responses: {
      /** @description Update a short URL */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UrlResponse"];
        };
      };
    };
  };
  UrlsController_deleteUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Delete a short URL successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PublicUrlsController_shortenUrl: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShortenUrlDto"];
      };
    };
    responses: {
      /** @description Created a new public short URL successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicUrlResponse"];
        };
      };
    };
  };
  PublicUrlsController_getUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get a short URL for a public access */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicUrlResponse"];
        };
      };
      /** @description Forbidden access to the URL */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenResponse"];
        };
      };
    };
  };
  PublicUrlsController_unlockUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnlockUrlDto"];
      };
    };
    responses: {
      /** @description Unlock a short URL for a public access */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicUrlResponse"];
        };
      };
    };
  };
  SubscriptionsController_getUserActiveSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get user active subscription successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubscriptionInfoResponse"];
        };
      };
    };
  };
  SubscriptionsController_getUserActiveSubscriptionCycles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get all active subscription cycles successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListSubscriptionCyclesResponse"];
        };
      };
    };
  };
  SubscriptionsController_getSubscriptionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get subscription by id successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubscriptionInfoResponse"];
        };
      };
    };
  };
  SubscriptionsController_getAllUserSubscriptionCycles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get all subscription cycles successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListSubscriptionCyclesResponse"];
        };
      };
    };
  };
  SubscriptionsController_getUserSubscriptionCycleById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        cycleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get subscription cycle by id successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubscriptionCycleResponse"];
        };
      };
    };
  };
  SubscriptionsController_deactivateSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deactivate Subscription plan successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubscriptionInfoResponse"];
        };
      };
    };
  };
  SubscriptionsController_upgradeSubscriptionPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpgradeSubscriptionDto"];
      };
    };
    responses: {
      /** @description Upgrade subscription plan successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubscriptionInfoResponse"];
        };
      };
    };
  };
  SubscriptionsController_getAllUpgradePlanOptions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get subscription upgrade options successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpgradePlanOptionResponse"];
        };
      };
    };
  };
  PaymentMethodsController_requestPaymentMethod: {
    parameters: {
      query: {
        successReturnUrl: string;
        failureReturnUrl: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get requested payment method successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPaymentMethodActionResponse"];
        };
      };
    };
  };
  PaymentMethodsController_getPaymentMethodById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get payment method by id successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodResponse"];
        };
      };
    };
  };
  PaymentMethodsController_getAllPaymentMethods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get all payment methods successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AllPaymentMethodsResponse"];
        };
      };
    };
  };
  PaymentMethodsController_createPaymentMethod: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePaymentMethodDto"];
      };
    };
    responses: {
      /** @description Create payment method successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodActionResponse"];
        };
      };
    };
  };
  PaymentMethodsController_sortPaymentMethods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SortPaymentMethodsDto"];
      };
    };
    responses: {
      /** @description Get payment method by id successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodResponse"];
        };
      };
    };
  };
  PublicPaymentMethodsController_addPaymentMethod: {
    parameters: {
      query: {
        token: string;
        successReturnUrl: string;
        failureReturnUrl: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PublicPaymentMethodsController_validatePaymentMethod: {
    parameters: {
      query: {
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidatePaymentMethodDto"];
      };
    };
    responses: {
      /** @description Validate payment method successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponse"];
        };
      };
    };
  };
  PublicPaymentMethodsController_createPaymentMethod: {
    parameters: {
      query: {
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePaymentMethodDto"];
      };
    };
    responses: {
      /** @description Create payment method successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentMethodActionResponse"];
        };
      };
    };
  };
  WebhooksController_handleXenditPaymentMethods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description successfully handling payment methods callback data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponse"];
        };
      };
    };
  };
  WebhooksController_handleXenditRecurring: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description successfully handling recurring plan callback data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OkResponse"];
        };
      };
    };
  };
  TransactionsController_getAllTransactions: {
    parameters: {
      query?: {
        /** @description Start date filter (YYYY-MM-DD) */
        startDate?: string;
        /** @description End date filter (YYYY-MM-DD) */
        endDate?: string;
        /** @description Transaction status filter (can include multiple) */
        status?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get all transactions successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListTransactionsResponse"];
        };
      };
    };
  };
  TransactionsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description get transaction by id successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListTransactionsResponse"];
        };
      };
    };
  };
}
